# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'extensions.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import legext_exercise

extState= 0
maxLegBend = ""
minLegBend = ""
tolerance = 0
extReps = 0
celebrate = False

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1500, 1000)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.hi_val = QtWidgets.QLabel(Form)
        self.hi_val.setGeometry(QtCore.QRect(890, 190, 501, 131))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(35)
        self.hi_val.setFont(font)
        self.hi_val.setAlignment(QtCore.Qt.AlignCenter)
        self.hi_val.setObjectName("hi_val")
        self.rep_label = QtWidgets.QLabel(Form)
        self.rep_label.setGeometry(QtCore.QRect(750, 90, 161, 101))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(30)
        self.rep_label.setFont(font)
        self.rep_label.setAlignment(QtCore.Qt.AlignCenter)
        self.rep_label.setObjectName("rep_label")
        self.lo_val = QtWidgets.QLabel(Form)
        self.lo_val.setGeometry(QtCore.QRect(890, 550, 501, 131))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(35)
        self.lo_val.setFont(font)
        self.lo_val.setAlignment(QtCore.Qt.AlignCenter)
        self.lo_val.setObjectName("lo_val")
        # self.ext_image = QtWidgets.QGraphicsView(Form)
        # self.ext_image.setGeometry(QtCore.QRect(10, 220, 711, 581))
        # self.ext_image.setStyleSheet("background-image: url(:/images/start.jpeg);")
        # self.ext_image.setObjectName("ext_image")
        self.ext_image = QtWidgets.QLabel(Form)
        self.ext_image.setGeometry(QtCore.QRect(160, 240, 671, 731))
        self.ext_image.setText("")
        self.ext_image.setPixmap(QtGui.QPixmap("startExt.jpeg"))
        self.ext_image.setScaledContents(False)
        self.ext_image.setAlignment(QtCore.Qt.AlignCenter)
        self.ext_image.setObjectName("lift_image")
        self.curr_val = QtWidgets.QLabel(Form)
        self.curr_val.setGeometry(QtCore.QRect(890, 370, 501, 131))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(35)
        self.curr_val.setFont(font)
        self.curr_val.setAlignment(QtCore.Qt.AlignCenter)
        self.curr_val.setObjectName("curr_val")
        self.ext_label = QtWidgets.QLabel(Form)
        self.ext_label.setGeometry(QtCore.QRect(300, 10, 1000, 101))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(50)
        self.ext_label.setFont(font)
        self.ext_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ext_label.setObjectName("ext_label")
        self.numReps = QtWidgets.QLabel(Form)
        self.numReps.setGeometry(QtCore.QRect(560, 90, 191, 101))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(30)
        self.numReps.setFont(font)
        self.numReps.setStyleSheet("color: rgb(224, 22, 61);")
        self.numReps.setAlignment(QtCore.Qt.AlignCenter)
        self.numReps.setObjectName("numReps")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.hi_val.setText(_translate("Form", "HIGH MAX VALUE"))
        self.rep_label.setText(_translate("Form", "REPS"))
        self.lo_val.setText(_translate("Form", "LOW MAX VALUE"))
        self.curr_val.setText(_translate("Form", "CURRENT VALUE"))
        self.ext_label.setText(_translate("Form", "LEG EXTENSIONS"))
        self.numReps.setText(_translate("Form", "numReps"))


    def displayTime(self, Form):
        dur = str(round(legext_exercise.getDuration(), 1))
        Form.ext_label.setText("Hold: " + dur)

    def extensions(self, Form, deg):
        global extState, celebrate
        extState = legext_exercise.legExtRep(int(deg), int(maxLegBend), int(minLegBend), tolerance, extState)
        if extState == 0:
            Form.ext_image.setPixmap(QtGui.QPixmap("endExt.jpeg"))
            Form.ext_label.setText("Extend your leg!")
        elif extState == 1:
            self.displayTime(Form)
        elif extState == 2:
            Form.ext_image.setPixmap(QtGui.QPixmap("startExt.jpeg"))
            Form.ext_label.setText("Bring your leg back down!")
        elif extState == 3:
            self.displayTime(Form)

        # print("extState: " + str(extState))
        curReps = legext_exercise.getReps()
        Form.curr_val.setText("Current Value: " + deg)
        Form.numReps.setText(str(curReps))
        if curReps == extReps:
            legext_exercise.zeroReps()
            celebrate = True

    def setValues(self, Form, max, min, tol, sReps, dur):
        global maxLegBend, minLegBend, tolerance, extReps
        maxLegBend = max
        minLegBend = min
        tolerance = tol
        extReps = sReps
        legext_exercise.setDuration(dur)

        Form.hi_val.setText("Straight Value: " + minLegBend)
        Form.lo_val.setText("Rest Value: " + maxLegBend)
        Form.rep_label.setText("Goal: " + str(extReps))

    def celebrateCheck(self):
        return celebrate

    def zeroCelebrate(self):
        global celebrate
        celebrate = False
        # print(celebrate)


import resources_rc_LegExt


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
