# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'exercise_home.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1500, 1000)
        Form.setMaximumSize(QtCore.QSize(1500, 1000))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(40)
        Form.setFont(font)
        Form.setStyleSheet("background-color: rgb(223, 223, 223);\n"
"background-color: rgb(255, 174, 176);")
        self.home_btn = QtWidgets.QPushButton(Form)
        self.home_btn.setGeometry(QtCore.QRect(30, 30, 141, 51))
        self.home_btn.setMaximumSize(QtCore.QSize(1500, 1000))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(30)
        font.setBold(False)
        font.setWeight(50)
        self.home_btn.setFont(font)
        self.home_btn.setStyleSheet("background-color: rgb(224, 22, 61);\n"
"color: rgb(255, 255, 255);")
        self.home_btn.setFlat(False)
        self.home_btn.setObjectName("home_btn")
        self.exit_btn = QtWidgets.QPushButton(Form)
        self.exit_btn.setGeometry(QtCore.QRect(30, 90, 141, 51))
        self.exit_btn.setMaximumSize(QtCore.QSize(1500, 1000))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(30)
        self.exit_btn.setFont(font)
        self.exit_btn.setStyleSheet("background-color: rgb(224, 22, 61);\n"
"color: rgb(255, 255, 255);")
        self.exit_btn.setObjectName("exit_btn")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(350, 10, 781, 161))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(50)
        self.label.setFont(font)
        self.label.setToolTipDuration(0)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.squat_btn = QtWidgets.QPushButton(Form)
        self.squat_btn.setGeometry(QtCore.QRect(100, 210, 581, 341))
        self.squat_btn.setMaximumSize(QtCore.QSize(581, 341))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(50)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.squat_btn.setFont(font)
        self.squat_btn.setAcceptDrops(False)
        self.squat_btn.setAutoFillBackground(False)
        self.squat_btn.setStyleSheet("border-image: url(:/images/squats.jpeg);\n"
"border-color: rgb(205, 175, 255);\n"
"font: 50pt \"Century Gothic\";")
        self.squat_btn.setText("")
        self.squat_btn.setObjectName("squat_btn")
        self.step_btn = QtWidgets.QPushButton(Form)
        self.step_btn.setGeometry(QtCore.QRect(100, 590, 581, 341))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.step_btn.setFont(font)
        self.step_btn.setStyleSheet("border-image: url(:/images/step_ups.jpeg);")
        self.step_btn.setText("")
        self.step_btn.setObjectName("step_btn")
        self.lift_btn = QtWidgets.QPushButton(Form)
        self.lift_btn.setGeometry(QtCore.QRect(810, 210, 581, 341))
        self.lift_btn.setStyleSheet("border-image: url(:/images/leg_lift.jpeg);")
        self.lift_btn.setText("")
        self.lift_btn.setObjectName("lift_btn")
        self.extend_btn = QtWidgets.QPushButton(Form)
        self.extend_btn.setGeometry(QtCore.QRect(810, 590, 581, 341))
        self.extend_btn.setStyleSheet("border-image: url(:/images/leg_ext.jpeg);")
        self.extend_btn.setText("")
        self.extend_btn.setObjectName("extend_btn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.home_btn.setText(_translate("Form", "HOME"))
        self.exit_btn.setText(_translate("Form", "EXIT"))
        self.label.setText(_translate("Form", "Choose your workout!"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
