# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'step_up.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import stepUpExercise

stepUpState = 0
maxLegBend = ""
minLegBend = ""
tolerance = 0
stepUpReps = 0
celebrate = False

class Ui_Form(object):
    #TODO Move Step Ups image lower, copy stuff from squats ui, implement stuff to main
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1500, 1000)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.step_label = QtWidgets.QLabel(Form)
        self.step_label.setGeometry(QtCore.QRect(580, 0, 321, 101))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(50)
        self.step_label.setFont(font)
        self.step_label.setAlignment(QtCore.Qt.AlignCenter)
        self.step_label.setObjectName("step_label")
        self.lo_val = QtWidgets.QLabel(Form)
        self.lo_val.setGeometry(QtCore.QRect(900, 550, 501, 131))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(35)
        self.lo_val.setFont(font)
        self.lo_val.setAlignment(QtCore.Qt.AlignCenter)
        self.lo_val.setObjectName("lo_val")
        self.step_image = QtWidgets.QGraphicsView(Form)
        self.step_image.setGeometry(QtCore.QRect(160, 240, 571, 731))
        self.step_image.setStyleSheet("border-image: url(:/images/start.jpeg);")
        self.step_image.setObjectName("step_image")
        self.numReps = QtWidgets.QLabel(Form)
        self.numReps.setGeometry(QtCore.QRect(570, 90, 191, 101))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(30)
        self.numReps.setFont(font)
        self.numReps.setStyleSheet("color: rgb(224, 22, 61);")
        self.numReps.setAlignment(QtCore.Qt.AlignCenter)
        self.numReps.setObjectName("numReps")
        self.curr_val = QtWidgets.QLabel(Form)
        self.curr_val.setGeometry(QtCore.QRect(900, 370, 501, 131))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(35)
        self.curr_val.setFont(font)
        self.curr_val.setAlignment(QtCore.Qt.AlignCenter)
        self.curr_val.setObjectName("curr_val")
        self.rep_label = QtWidgets.QLabel(Form)
        self.rep_label.setGeometry(QtCore.QRect(760, 90, 161, 101))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(30)
        self.rep_label.setFont(font)
        self.rep_label.setAlignment(QtCore.Qt.AlignCenter)
        self.rep_label.setObjectName("rep_label")
        self.hi_val = QtWidgets.QLabel(Form)
        self.hi_val.setGeometry(QtCore.QRect(900, 190, 501, 131))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(35)
        self.hi_val.setFont(font)
        self.hi_val.setAlignment(QtCore.Qt.AlignCenter)
        self.hi_val.setObjectName("hi_val")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.step_label.setText(_translate("Form", "STEP UPS"))
        self.lo_val.setText(_translate("Form", "LOW MAX VALUE"))
        self.numReps.setText(_translate("Form", "numReps"))
        self.curr_val.setText(_translate("Form", "CURRENT VALUE"))
        self.rep_label.setText(_translate("Form", "REPS"))
        self.hi_val.setText(_translate("Form", "HIGH MAX VALUE"))
    
    def displayTime(self, Form):
        dur = str(round(stepUpExercise.getDuration(), 1))
        Form.step_label.setText("Hold: " + dur)
    
    def setValues(self, Form, max, min, tol, sReps, dur):
        global maxLegBend, minLegBend, tolerance, stepUpReps
        maxLegBend = max
        minLegBend = min
        tolerance = tol
        stepUpReps = sReps
        stepUpExercise.setDuration(dur)

        Form.hi_val.setText("StepUp Value: " + minLegBend)
        Form.lo_val.setText("StepRest Value: " + maxLegBend)
        Form.rep_label.setText("Goal: " + str(stepUpReps))
        
    def celebrateCheck(self):
        return celebrate

    def zeroCelebrate(self):
        global celebrate
        celebrate = False
        # print(celebrate)
        
    def stepUps(self, Form, deg):
        global stepUpState, celebrate
        stepUpState = stepUpExercise.stepUpRep(int(deg), int(maxLegBend), int(minLegBend), tolerance, stepUpState)
        if stepUpState == 0:
            Form.step_image.setStyleSheet("border-image: url(:/images/start.jpeg);")
            Form.step_label.setText("Rest Step!")
        elif stepUpState == 1:
            self.displayTime(Form)
        elif stepUpState == 2:
            Form.step_image.setStyleSheet("border-image: url(:/images/end.jpeg);")
            Form.step_label.setText("Step Up!")
        elif stepUpState == 3:
            self.displayTime(Form)

        # print("StepUpState: " + str(stepUpState))
        curReps = stepUpExercise.getReps()
        Form.curr_val.setText("Current Value: " + deg)
        Form.numReps.setText(str(curReps))
        if curReps == stepUpReps:
            stepUpExercise.zeroReps()
            celebrate = True
import resources_rc_StepUp


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
