# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lift.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, QtSerialPort
from pynput.keyboard import Key, Controller, Listener
import leglift_exercise
import resources_rc_LegLift
import time

legLiftState = 0
maxLegBend = ""
minLegBend = ""
tolerance = 0
legliftReps = 0
celebrate = False

class Ui_Form(object):


    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1500, 1000)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lift_label = QtWidgets.QLabel(Form)
        self.lift_label.setGeometry(QtCore.QRect(300, 0, 1000, 101))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(50)
        self.lift_label.setFont(font)
        self.lift_label.setAlignment(QtCore.Qt.AlignCenter)
        self.lift_label.setObjectName("lift_label")
        self.lo_val = QtWidgets.QLabel(Form)
        self.lo_val.setGeometry(QtCore.QRect(900, 550, 501, 131))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(35)
        self.lo_val.setFont(font)
        self.lo_val.setAlignment(QtCore.Qt.AlignCenter)
        self.lo_val.setObjectName("lo_val")
        # self.lift_image = QtWidgets.QGraphicsView(Form)
        # self.lift_image.setGeometry(QtCore.QRect(160, 240, 571, 731))
        # self.lift_image.setStyleSheet("background-image: url(startLL.jpeg);")
        # self.lift_image.setObjectName("lift_image")
        self.lift_image = QtWidgets.QLabel(Form)
        self.lift_image.setGeometry(QtCore.QRect(160, 240, 671, 731))
        self.lift_image.setText("")
        self.lift_image.setPixmap(QtGui.QPixmap("endLL.jpeg"))
        self.lift_image.setScaledContents(False)
        self.lift_image.setAlignment(QtCore.Qt.AlignCenter)
        self.lift_image.setObjectName("lift_image")
        self.numReps = QtWidgets.QLabel(Form)
        self.numReps.setGeometry(QtCore.QRect(570, 90, 191, 101))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(30)
        self.numReps.setFont(font)
        self.numReps.setStyleSheet("color: rgb(224, 22, 61);")
        self.numReps.setAlignment(QtCore.Qt.AlignCenter)
        self.numReps.setObjectName("numReps")
        self.curr_val = QtWidgets.QLabel(Form)
        self.curr_val.setGeometry(QtCore.QRect(900, 370, 501, 131))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(35)
        self.curr_val.setFont(font)
        self.curr_val.setAlignment(QtCore.Qt.AlignCenter)
        self.curr_val.setObjectName("curr_val")
        self.rep_label = QtWidgets.QLabel(Form)
        self.rep_label.setGeometry(QtCore.QRect(760, 90, 161, 101))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(30)
        self.rep_label.setFont(font)
        self.rep_label.setAlignment(QtCore.Qt.AlignCenter)
        self.rep_label.setObjectName("rep_label")
        self.hi_val = QtWidgets.QLabel(Form)
        self.hi_val.setGeometry(QtCore.QRect(900, 190, 501, 131))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(35)
        self.hi_val.setFont(font)
        self.hi_val.setAlignment(QtCore.Qt.AlignCenter)
        self.hi_val.setObjectName("hi_val")
        self.lift_image.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lift_label.setText(_translate("Form", "LEG LIFTS"))
        self.lo_val.setText(_translate("Form", ""))
        self.numReps.setText(_translate("Form", "numReps"))
        self.curr_val.setText(_translate("Form", "CURRENT VALUE"))
        self.rep_label.setText(_translate("Form", "REPS"))
        self.hi_val.setText(_translate("Form", "LOW MAX VALUE"))

    def setValues(self, Form, max, min, tol, sReps, dur):
        global maxLegBend, minLegBend, tolerance, legliftReps
        maxLegBend = max
        minLegBend = min
        tolerance = tol
        legliftReps = sReps
        leglift_exercise.setDuration(dur)

        Form.hi_val.setText("Straight Value: " + minLegBend)
        # Form.lo_val.setText("Squat Value: " + maxLegBend)
        Form.rep_label.setText("Goal: " + str(legliftReps))

    def displayTime(self, Form):
        dur = str(round(leglift_exercise.getDuration(), 1))
        Form.lift_label.setText("Hold: " + dur)

    def celebrateCheck(self):
        return celebrate

    def zeroCelebrate(self):
        global celebrate
        celebrate = False
        # print(celebrate)

    def lifts(self, Form, deg, cap):
        global legLiftState, celebrate
        legLiftState = leglift_exercise.lift(int(deg), int(minLegBend), tolerance, cap, legLiftState)
        if legLiftState == 0:
            Form.lift_image.setPixmap(QtGui.QPixmap("endLL.jpeg"))
            Form.lift_label.setText("Lift leg and Press '0'!")
        elif legLiftState == 1:
            self.displayTime(Form)
        elif legLiftState == 2:
            Form.lift_image.setPixmap(QtGui.QPixmap("startLL.jpeg"))
            Form.lift_label.setText("Rest your leg and Press '0'!")
        elif legLiftState == 3:
            self.displayTime(Form)

        # print("legLiftState: " + str(legLiftState))
        curReps = leglift_exercise.getReps()
        Form.curr_val.setText("Current Value: " + deg)
        Form.numReps.setText(str(curReps))
        if curReps == legliftReps:
            leglift_exercise.zeroReps()
            celebrate = True






if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
