# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, QtSerialPort
from PyQt5.QtCore import QEvent
from pynput.keyboard import Key, Controller, Listener
import time
import sys

# #Import different sections back and front ends
# sys.path.append('Home')
# import main

sys.path.append('Exercise')
import exer_home

sys.path.append('Squat')
import squats

sys.path.append('StepUp')
import step_up

sys.path.append('LegLift')
import lift

sys.path.append('LegExtend')
#TODO: import leg lift stuff

#Variables
cap = ""
deg = ""

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1500, 1000)
        Form.setStyleSheet("background: url(:/images/home.JPG);")
        self.how_to = QtWidgets.QLabel(Form)
        self.how_to.setGeometry(QtCore.QRect(530, 130, 441, 61))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(40)
        self.how_to.setFont(font)
        self.how_to.setStyleSheet("background-image: url(:/images/transparent.png);")
        self.how_to.setObjectName("how_to")
        self.welcome = QtWidgets.QLabel(Form)
        self.welcome.setGeometry(QtCore.QRect(1020, 80, 441, 61))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(40)
        self.welcome.setFont(font)
        self.welcome.setStyleSheet("background-image: url(:/images/transparent.png);")
        self.welcome.setAlignment(QtCore.Qt.AlignCenter)
        self.welcome.setObjectName("welcome")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(550, 210, 421, 511))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(30)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-image: url(:/images/transparent.png);")
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.cal_btn = QtWidgets.QPushButton(Form)
        self.cal_btn.setGeometry(QtCore.QRect(1110, 220, 251, 101))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(25)
        self.cal_btn.setFont(font)
        self.cal_btn.setStyleSheet("background-color: rgb(238, 17, 51);\n"
"background-image: url(:/images/transparent.png);\n"
"color: rgb(255, 255, 255);")
        self.cal_btn.setObjectName("cal_btn")
        self.prog_btn = QtWidgets.QPushButton(Form)
        self.prog_btn.setGeometry(QtCore.QRect(1110, 380, 251, 101))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(25)
        self.prog_btn.setFont(font)
        self.prog_btn.setStyleSheet("background-color: rgb(238, 17, 51);\n"
"background-image: url(:/images/transparent.png);\n"
"color: rgb(255, 255, 255);")
        self.prog_btn.setObjectName("prog_btn")
        self.exercise_btn = QtWidgets.QPushButton(Form)
        self.exercise_btn.setGeometry(QtCore.QRect(1110, 540, 251, 101))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(25)
        self.exercise_btn.setFont(font)
        self.exercise_btn.setStyleSheet("background-color: rgb(238, 17, 51);\n"
"background-image: url(:/images/transparent.png);\n"
"color: rgb(255, 255, 255);")
        self.exercise_btn.setObjectName("exercise_btn")
        self.exit_btn = QtWidgets.QPushButton(Form)
        self.exit_btn.setGeometry(QtCore.QRect(1110, 700, 251, 101))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(25)
        self.exit_btn.setFont(font)
        self.exit_btn.setStyleSheet("background-color: rgb(238, 17, 51);\n"
"background-image: url(:/images/transparent.png);\n"
"color: rgb(255, 255, 255);")
        self.exit_btn.setObjectName("exit_btn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.action_items()
        self.serial = QtSerialPort.QSerialPort(
            'COM3',
            baudRate=QtSerialPort.QSerialPort.Baud115200,
            readyRead=self.receive
        )

        if not self.serial.isOpen():
            if not self.serial.open(QtCore.QIODevice.ReadWrite):
                print("Serial Started")

    def receive(self):
        while self.serial.canReadLine():
            text = self.serial.readLine().data().decode()
            text = text.rstrip('\r\n')
            tempText = text.rsplit(" ")

            print(text)

            type = tempText[0]
            value = tempText[1]

            if type[0] == 'B':
                deg = value.split(".")[0]
                # print(deg)
            elif type[0] == 'C':
                cap = value
                # print(cap)

            squat_ui.squatValues(deg)
            #Implement functionality here


    def action_items(self):
        #From this UI
        self.exercise_btn.clicked.connect(self.goExercise)

        #From Exercise UI
        exer_ui.squat_btn.clicked.connect(self.goSquat)
        exer_ui.step_btn.clicked.connect(self.goStep)
        exer_ui.lift_btn.clicked.connect(self.goLift)
        # exer_ui.extend_btn.clicked.connect(self.goExtend)
        exer_ui.home_btn.clicked.connect(self.goHome)
        exer_ui.exit_btn.clicked.connect(exit)
        # exer_ui.squat_btn.clicked.connect(self.goSquat)




    def goExercise(self):
        self.hideAll()
        Exercise_Form.show()
        print("Going to Exercise GUI")

    def goSquat(self):
        self.hideAll()
        Squat_Form.show()
        print("Going to Squat GUI")

    def goStep(self):
        self.hideAll()
        StepUp_Form.show()
        print("Going to Step Up GUI")

    def goLift(self):
        self.hideAll()
        LegLift_Form.show()
        print("Going to Leg Lift GUI")

    # def goExtend(self):
    #     self.hideAll()
    #     LegExtend_Form.show()
    #     print("Going to Leg Extend GUI")

    def goHome(self):
        self.hideAll()
        Home_Form.show()
        print("Going HOME")

    def hideAll(self):
        Home_Form.hide()
        Exercise_Form.hide()
        Squat_Form.hide()
        StepUp_Form.hide()
        LegLift_Form.hide()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.how_to.setText(_translate("Form", "HOW TO USE APP"))
        self.welcome.setText(_translate("Form", "WELCOME"))
        self.label_3.setText(_translate("Form", "1. Calibrate your device\n"
"2. Set your knee\'s maximum bend angle\n"
"3. Start your workouts!"))
        self.cal_btn.setText(_translate("Form", "Calibrate"))
        self.prog_btn.setText(_translate("Form", "Progress"))
        self.exercise_btn.setText(_translate("Form", "Exercise"))
        self.exit_btn.setText(_translate("Form", "Exit"))

import resources_rc_Home

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    # print(SquatExercise.squatRep(200, 100, 110, 10, 2))

    #Exercises
    Exercise_Form = QtWidgets.QWidget()
    exer_ui = exer_home.Ui_Form()
    exer_ui.setupUi(Exercise_Form)

    #Squats
    Squat_Form = QtWidgets.QWidget()
    squat_ui = squats.Ui_Form()
    squat_ui.setupUi(Squat_Form)

    #Step Up
    StepUp_Form = QtWidgets.QWidget()
    step_up_ui = step_up.Ui_Form()
    step_up_ui.setupUi(StepUp_Form)

    #Leg_Lift
    LegLift_Form = QtWidgets.QWidget()
    leg_lift_ui = lift.Ui_Form()
    leg_lift_ui.setupUi(LegLift_Form)

    # #Leg_Extend
    # LegExtend_Form = QtWidgets.QWidget()
    # leg_extend_ui = lift.Ui_Form()
    # leg_extend_ui.setupUi(LegLift_Form)

    #Home
    Home_Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Home_Form)


    Home_Form.show()
    sys.exit(app.exec_())

