# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1500, 1000)
        Form.setStyleSheet("background: url(:/images/home.JPG);")
        self.how_to = QtWidgets.QLabel(Form)
        self.how_to.setGeometry(QtCore.QRect(530, 130, 441, 61))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(40)
        self.how_to.setFont(font)
        self.how_to.setStyleSheet("background-image: url(:/images/transparent.png);")
        self.how_to.setObjectName("how_to")
        self.welcome = QtWidgets.QLabel(Form)
        self.welcome.setGeometry(QtCore.QRect(1020, 80, 441, 61))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(40)
        self.welcome.setFont(font)
        self.welcome.setStyleSheet("background-image: url(:/images/transparent.png);")
        self.welcome.setAlignment(QtCore.Qt.AlignCenter)
        self.welcome.setObjectName("welcome")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(550, 210, 421, 511))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(30)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-image: url(:/images/transparent.png);")
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.cal_btn = QtWidgets.QPushButton(Form)
        self.cal_btn.setGeometry(QtCore.QRect(1110, 220, 251, 101))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(25)
        self.cal_btn.setFont(font)
        self.cal_btn.setStyleSheet("background-color: rgb(238, 17, 51);\n"
"background-image: url(:/images/transparent.png);\n"
"color: rgb(255, 255, 255);")
        self.cal_btn.setObjectName("cal_btn")
        self.prog_btn = QtWidgets.QPushButton(Form)
        self.prog_btn.setGeometry(QtCore.QRect(1110, 380, 251, 101))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(25)
        self.prog_btn.setFont(font)
        self.prog_btn.setStyleSheet("background-color: rgb(238, 17, 51);\n"
"background-image: url(:/images/transparent.png);\n"
"color: rgb(255, 255, 255);")
        self.prog_btn.setObjectName("prog_btn")
        self.exercise_btn = QtWidgets.QPushButton(Form)
        self.exercise_btn.setGeometry(QtCore.QRect(1110, 540, 251, 101))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(25)
        self.exercise_btn.setFont(font)
        self.exercise_btn.setStyleSheet("background-color: rgb(238, 17, 51);\n"
"background-image: url(:/images/transparent.png);\n"
"color: rgb(255, 255, 255);")
        self.exercise_btn.setObjectName("exercise_btn")
        self.exit_btn = QtWidgets.QPushButton(Form)
        self.exit_btn.setGeometry(QtCore.QRect(1110, 700, 251, 101))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(25)
        self.exit_btn.setFont(font)
        self.exit_btn.setStyleSheet("background-color: rgb(238, 17, 51);\n"
"background-image: url(:/images/transparent.png);\n"
"color: rgb(255, 255, 255);")
        self.exit_btn.setObjectName("exit_btn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.how_to.setText(_translate("Form", "HOW TO USE APP"))
        self.welcome.setText(_translate("Form", "WELCOME"))
        self.label_3.setText(_translate("Form", "1. Calibrate your device\n"
"2. Set your knee\'s maximum bend angle\n"
"3. Start your workouts!"))
        self.cal_btn.setText(_translate("Form", "Calibrate"))
        self.prog_btn.setText(_translate("Form", "Progress"))
        self.exercise_btn.setText(_translate("Form", "Exercise"))
        self.exit_btn.setText(_translate("Form", "Exit"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
