# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'squats.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, QtSerialPort
from pynput.keyboard import Key, Controller, Listener
import SquatExercise
import time

squatState = 0
maxLegBend = ""
minLegBend = ""
tolerance = 0
squatReps = 0
celebrate = False

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1493, 1000)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.squat_image = QtWidgets.QGraphicsView(Form)
        self.squat_image.setGeometry(QtCore.QRect(160, 240, 631, 621))
        self.squat_image.setStyleSheet("background-image: url(:/images/1st.jpeg);")
        self.squat_image.setObjectName("squat_image")
        self.squat_label = QtWidgets.QLabel(Form)
        self.squat_label.setGeometry(QtCore.QRect(495, 40, 610, 101))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(50)
        self.squat_label.setFont(font)
        self.squat_label.setAlignment(QtCore.Qt.AlignCenter)
        self.squat_label.setObjectName("squat_label")
        self.rep_label = QtWidgets.QLabel(Form)
        self.rep_label.setGeometry(QtCore.QRect(790, 130, 161, 101))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(30)
        self.rep_label.setFont(font)
        self.rep_label.setAlignment(QtCore.Qt.AlignCenter)
        self.rep_label.setObjectName("rep_label")
        self.numReps = QtWidgets.QLabel(Form)
        self.numReps.setGeometry(QtCore.QRect(600, 130, 191, 101))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(30)
        self.numReps.setFont(font)
        self.numReps.setStyleSheet("color: rgb(224, 22, 61);")
        self.numReps.setAlignment(QtCore.Qt.AlignCenter)
        self.numReps.setObjectName("numReps")
        self.hi_val = QtWidgets.QLabel(Form)
        self.hi_val.setGeometry(QtCore.QRect(930, 230, 501, 131))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(35)
        self.hi_val.setFont(font)
        self.hi_val.setAlignment(QtCore.Qt.AlignCenter)
        self.hi_val.setObjectName("hi_val")
        self.curr_val = QtWidgets.QLabel(Form)
        self.curr_val.setGeometry(QtCore.QRect(930, 410, 501, 131))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(35)
        self.curr_val.setFont(font)
        self.curr_val.setAlignment(QtCore.Qt.AlignCenter)
        self.curr_val.setObjectName("curr_val")
        self.lo_val = QtWidgets.QLabel(Form)
        self.lo_val.setGeometry(QtCore.QRect(930, 590, 501, 131))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(35)
        self.lo_val.setFont(font)
        self.lo_val.setAlignment(QtCore.Qt.AlignCenter)
        self.lo_val.setObjectName("lo_val")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def displayTime(self, Form):
        dur = str(round(SquatExercise.getDuration(), 1))
        Form.squat_label.setText("Hold: " + dur)

    def squats(self, Form, deg):
        global squatState, celebrate
        squatState = SquatExercise.squatRep(int(deg), int(maxLegBend), int(minLegBend), tolerance, squatState)
        if squatState == 0:
            Form.squat_image.setStyleSheet("background-image: url(:/images/1st.jpeg);")
            Form.squat_label.setText("Squat Down!")
        elif squatState == 1:
            self.displayTime(Form)
        elif squatState == 2:
            Form.squat_image.setStyleSheet("background-image: url(:/images/2nd.jpeg);")
            Form.squat_label.setText("Go Up!")
        elif squatState == 3:
            self.displayTime(Form)

        # print("SquatState: " + str(squatState))
        curReps = SquatExercise.getReps()
        Form.curr_val.setText("Current Value: " + deg)
        Form.numReps.setText(str(curReps))
        if curReps == squatReps:
            SquatExercise.zeroReps()
            celebrate = True

    def setValues(self, Form, max, min, tol, sReps, dur):
        global maxLegBend, minLegBend, tolerance, squatReps
        maxLegBend = max
        minLegBend = min
        tolerance = tol
        squatReps = sReps
        SquatExercise.setDuration(dur)

        Form.hi_val.setText("Straight Value: " + minLegBend)
        Form.lo_val.setText("Squat Value: " + maxLegBend)
        Form.rep_label.setText("Goal: " + str(squatReps))

    def celebrateCheck(self):
        return celebrate

    def zeroCelebrate(self):
        global celebrate
        celebrate = False
        # print(celebrate)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Squat Exercise"))
        self.squat_label.setText(_translate("Form", "SQUATS"))
        self.rep_label.setText(_translate("Form", "REPS"))
        self.numReps.setText(_translate("Form", "numReps"))
        self.hi_val.setText(_translate("Form", "HIGH MAX VALUE"))
        self.curr_val.setText(_translate("Form", "CURRENT VALUE"))
        self.lo_val.setText(_translate("Form", "LOW MAX VALUE"))
import resources_rc_Squat

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
