# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'extensions.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1500, 1000)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.hi_val = QtWidgets.QLabel(Form)
        self.hi_val.setGeometry(QtCore.QRect(890, 190, 501, 131))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(35)
        self.hi_val.setFont(font)
        self.hi_val.setAlignment(QtCore.Qt.AlignCenter)
        self.hi_val.setObjectName("hi_val")
        self.rep_label = QtWidgets.QLabel(Form)
        self.rep_label.setGeometry(QtCore.QRect(750, 90, 161, 101))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(30)
        self.rep_label.setFont(font)
        self.rep_label.setAlignment(QtCore.Qt.AlignCenter)
        self.rep_label.setObjectName("rep_label")
        self.lo_val = QtWidgets.QLabel(Form)
        self.lo_val.setGeometry(QtCore.QRect(890, 550, 501, 131))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(35)
        self.lo_val.setFont(font)
        self.lo_val.setAlignment(QtCore.Qt.AlignCenter)
        self.lo_val.setObjectName("lo_val")
        self.ext_image = QtWidgets.QGraphicsView(Form)
        self.ext_image.setGeometry(QtCore.QRect(10, 220, 711, 581))
        self.ext_image.setStyleSheet("background-image: url(:/images/start.jpeg);")
        self.ext_image.setObjectName("ext_image")
        self.curr_val = QtWidgets.QLabel(Form)
        self.curr_val.setGeometry(QtCore.QRect(890, 370, 501, 131))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(35)
        self.curr_val.setFont(font)
        self.curr_val.setAlignment(QtCore.Qt.AlignCenter)
        self.curr_val.setObjectName("curr_val")
        self.ext_label = QtWidgets.QLabel(Form)
        self.ext_label.setGeometry(QtCore.QRect(470, 10, 571, 101))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(50)
        self.ext_label.setFont(font)
        self.ext_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ext_label.setObjectName("ext_label")
        self.numReps = QtWidgets.QLabel(Form)
        self.numReps.setGeometry(QtCore.QRect(560, 90, 191, 101))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(30)
        self.numReps.setFont(font)
        self.numReps.setStyleSheet("color: rgb(224, 22, 61);")
        self.numReps.setAlignment(QtCore.Qt.AlignCenter)
        self.numReps.setObjectName("numReps")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.hi_val.setText(_translate("Form", "HIGH MAX VALUE"))
        self.rep_label.setText(_translate("Form", "REPS"))
        self.lo_val.setText(_translate("Form", "LOW MAX VALUE"))
        self.curr_val.setText(_translate("Form", "CURRENT VALUE"))
        self.ext_label.setText(_translate("Form", "LEG EXTENSIONS"))
        self.numReps.setText(_translate("Form", "numReps"))
import RESOURCES_rc
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
